//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.7.3081.0.
// 
namespace Scalesoft.Dasta.Definitions.v4_19_02 {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:cz-mzcr:ns:dasta:ds4:ds_dasta")]
    [System.Xml.Serialization.XmlRootAttribute("a", Namespace="urn:cz-mzcr:ns:dasta:ds4:ds_dasta", IsNullable=false)]
    public partial class aType {
        
        private dat_xxType dat_odField;
        
        private dat_xxType dat_doField;
        
        private string o_jmenoField;
        
        private string o_prijmeniField;
        
        private string o_titul_predField;
        
        private string o_titul_zaField;
        
        private string f_jmenoField;
        
        private string f_icoField;
        
        private string jmenoField;
        
        private string adrField;
        
        private string dop1Field;
        
        private string dop2Field;
        
        private string pscField;
        
        private string mestoField;
        
        private string statField;
        
        private string stat_textField;
        
        private gpsType gpsField;
        
        private string vztahField;
        
        private string k_osoba_klicField;
        
        private string k_osoba_textField;
        
        private string k_osoba_poznField;
        
        private string k_osoba_typField;
        
        private string k_osoba_pravoField;
        
        private string iclField;
        
        private string id_zpField;
        
        private string poznField;
        
        private autorType autorField;
        
        private asType[] asField;
        
        private AnyType aAnyField;
        
        private string typField;
        
        private string ind_kontField;
        
        private aTypeSr_typ sr_typField;
        
        private bool sr_typFieldSpecified;
        
        private string sr_poisField;
        
        private string sr_kodField;
        
        private string sr_lekarField;
        
        /// <remarks/>
        public dat_xxType dat_od {
            get {
                return this.dat_odField;
            }
            set {
                this.dat_odField = value;
            }
        }
        
        /// <remarks/>
        public dat_xxType dat_do {
            get {
                return this.dat_doField;
            }
            set {
                this.dat_doField = value;
            }
        }
        
        /// <remarks/>
        public string o_jmeno {
            get {
                return this.o_jmenoField;
            }
            set {
                this.o_jmenoField = value;
            }
        }
        
        /// <remarks/>
        public string o_prijmeni {
            get {
                return this.o_prijmeniField;
            }
            set {
                this.o_prijmeniField = value;
            }
        }
        
        /// <remarks/>
        public string o_titul_pred {
            get {
                return this.o_titul_predField;
            }
            set {
                this.o_titul_predField = value;
            }
        }
        
        /// <remarks/>
        public string o_titul_za {
            get {
                return this.o_titul_zaField;
            }
            set {
                this.o_titul_zaField = value;
            }
        }
        
        /// <remarks/>
        public string f_jmeno {
            get {
                return this.f_jmenoField;
            }
            set {
                this.f_jmenoField = value;
            }
        }
        
        /// <remarks/>
        public string f_ico {
            get {
                return this.f_icoField;
            }
            set {
                this.f_icoField = value;
            }
        }
        
        /// <remarks/>
        public string jmeno {
            get {
                return this.jmenoField;
            }
            set {
                this.jmenoField = value;
            }
        }
        
        /// <remarks/>
        public string adr {
            get {
                return this.adrField;
            }
            set {
                this.adrField = value;
            }
        }
        
        /// <remarks/>
        public string dop1 {
            get {
                return this.dop1Field;
            }
            set {
                this.dop1Field = value;
            }
        }
        
        /// <remarks/>
        public string dop2 {
            get {
                return this.dop2Field;
            }
            set {
                this.dop2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string psc {
            get {
                return this.pscField;
            }
            set {
                this.pscField = value;
            }
        }
        
        /// <remarks/>
        public string mesto {
            get {
                return this.mestoField;
            }
            set {
                this.mestoField = value;
            }
        }
        
        /// <remarks/>
        public string stat {
            get {
                return this.statField;
            }
            set {
                this.statField = value;
            }
        }
        
        /// <remarks/>
        public string stat_text {
            get {
                return this.stat_textField;
            }
            set {
                this.stat_textField = value;
            }
        }
        
        /// <remarks/>
        public gpsType gps {
            get {
                return this.gpsField;
            }
            set {
                this.gpsField = value;
            }
        }
        
        /// <remarks/>
        public string vztah {
            get {
                return this.vztahField;
            }
            set {
                this.vztahField = value;
            }
        }
        
        /// <remarks/>
        public string k_osoba_klic {
            get {
                return this.k_osoba_klicField;
            }
            set {
                this.k_osoba_klicField = value;
            }
        }
        
        /// <remarks/>
        public string k_osoba_text {
            get {
                return this.k_osoba_textField;
            }
            set {
                this.k_osoba_textField = value;
            }
        }
        
        /// <remarks/>
        public string k_osoba_pozn {
            get {
                return this.k_osoba_poznField;
            }
            set {
                this.k_osoba_poznField = value;
            }
        }
        
        /// <remarks/>
        public string k_osoba_typ {
            get {
                return this.k_osoba_typField;
            }
            set {
                this.k_osoba_typField = value;
            }
        }
        
        /// <remarks/>
        public string k_osoba_pravo {
            get {
                return this.k_osoba_pravoField;
            }
            set {
                this.k_osoba_pravoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string icl {
            get {
                return this.iclField;
            }
            set {
                this.iclField = value;
            }
        }
        
        /// <remarks/>
        public string id_zp {
            get {
                return this.id_zpField;
            }
            set {
                this.id_zpField = value;
            }
        }
        
        /// <remarks/>
        public string pozn {
            get {
                return this.poznField;
            }
            set {
                this.poznField = value;
            }
        }
        
        /// <remarks/>
        public autorType autor {
            get {
                return this.autorField;
            }
            set {
                this.autorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("as")]
        public asType[] @as {
            get {
                return this.asField;
            }
            set {
                this.asField = value;
            }
        }
        
        /// <remarks/>
        public AnyType aAny {
            get {
                return this.aAnyField;
            }
            set {
                this.aAnyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string typ {
            get {
                return this.typField;
            }
            set {
                this.typField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ind_kont {
            get {
                return this.ind_kontField;
            }
            set {
                this.ind_kontField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public aTypeSr_typ sr_typ {
            get {
                return this.sr_typField;
            }
            set {
                this.sr_typField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool sr_typSpecified {
            get {
                return this.sr_typFieldSpecified;
            }
            set {
                this.sr_typFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string sr_pois {
            get {
                return this.sr_poisField;
            }
            set {
                this.sr_poisField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string sr_kod {
            get {
                return this.sr_kodField;
            }
            set {
                this.sr_kodField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string sr_lekar {
            get {
                return this.sr_lekarField;
            }
            set {
                this.sr_lekarField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:cz-mzcr:ns:dasta:ds4:ds_type")]
    public partial class dat_xxType {
        
        private string formatField;
        
        private string valueField;
        
        public dat_xxType() {
            this.formatField = "DTS";
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute("DTS")]
        public string format {
            get {
                return this.formatField;
            }
            set {
                this.formatField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:cz-mzcr:ns:dasta:ds4:ds_dasta")]
    public partial class chyba_pdType {
        
        private chyba_pdTypeKod kodField;
        
        private string lokalizaceField;
        
        private chyba_pdTypeOsetreni osetreniField;
        
        private bool osetreniFieldSpecified;
        
        private string popisField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public chyba_pdTypeKod kod {
            get {
                return this.kodField;
            }
            set {
                this.kodField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string lokalizace {
            get {
                return this.lokalizaceField;
            }
            set {
                this.lokalizaceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public chyba_pdTypeOsetreni osetreni {
            get {
                return this.osetreniField;
            }
            set {
                this.osetreniField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool osetreniSpecified {
            get {
                return this.osetreniFieldSpecified;
            }
            set {
                this.osetreniFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string popis {
            get {
                return this.popisField;
            }
            set {
                this.popisField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:cz-mzcr:ns:dasta:ds4:ds_dasta")]
    public enum chyba_pdTypeKod {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("000")]
        Item000,
        
        /// <remarks/>
        X01,
        
        /// <remarks/>
        X02,
        
        /// <remarks/>
        X03,
        
        /// <remarks/>
        X04,
        
        /// <remarks/>
        X05,
        
        /// <remarks/>
        X99,
        
        /// <remarks/>
        D01,
        
        /// <remarks/>
        D02,
        
        /// <remarks/>
        D03,
        
        /// <remarks/>
        D04,
        
        /// <remarks/>
        D99,
        
        /// <remarks/>
        A01,
        
        /// <remarks/>
        A99,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:cz-mzcr:ns:dasta:ds4:ds_dasta")]
    public enum chyba_pdTypeOsetreni {
        
        /// <remarks/>
        I,
        
        /// <remarks/>
        O,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:cz-mzcr:ns:dasta:ds4:ds_dasta")]
    public partial class pdType {
        
        private chyba_pdType[] chyba_pdField;
        
        private asType asField;
        
        private dat_xxType dat_osField;
        
        private dat_xxType dat_psField;
        
        private string id_souborField;
        
        private pdTypeStav stavField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("chyba_pd")]
        public chyba_pdType[] chyba_pd {
            get {
                return this.chyba_pdField;
            }
            set {
                this.chyba_pdField = value;
            }
        }
        
        /// <remarks/>
        public asType @as {
            get {
                return this.asField;
            }
            set {
                this.asField = value;
            }
        }
        
        /// <remarks/>
        public dat_xxType dat_os {
            get {
                return this.dat_osField;
            }
            set {
                this.dat_osField = value;
            }
        }
        
        /// <remarks/>
        public dat_xxType dat_ps {
            get {
                return this.dat_psField;
            }
            set {
                this.dat_psField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string id_soubor {
            get {
                return this.id_souborField;
            }
            set {
                this.id_souborField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public pdTypeStav stav {
            get {
                return this.stavField;
            }
            set {
                this.stavField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:cz-mzcr:ns:dasta:ds4:ds_dasta")]
    [System.Xml.Serialization.XmlRootAttribute("as", Namespace="urn:cz-mzcr:ns:dasta:ds4:ds_dasta", IsNullable=false)]
    public partial class asType {
        
        private string obsahField;
        
        private string vnitrniField;
        
        private string sdeleniField;
        
        private AnyType asAnyField;
        
        private asTypePoradi poradiField;
        
        private bool poradiFieldSpecified;
        
        private asTypeTyp typField;
        
        /// <remarks/>
        public string obsah {
            get {
                return this.obsahField;
            }
            set {
                this.obsahField = value;
            }
        }
        
        /// <remarks/>
        public string vnitrni {
            get {
                return this.vnitrniField;
            }
            set {
                this.vnitrniField = value;
            }
        }
        
        /// <remarks/>
        public string sdeleni {
            get {
                return this.sdeleniField;
            }
            set {
                this.sdeleniField = value;
            }
        }
        
        /// <remarks/>
        public AnyType asAny {
            get {
                return this.asAnyField;
            }
            set {
                this.asAnyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public asTypePoradi poradi {
            get {
                return this.poradiField;
            }
            set {
                this.poradiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool poradiSpecified {
            get {
                return this.poradiFieldSpecified;
            }
            set {
                this.poradiFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public asTypeTyp typ {
            get {
                return this.typField;
            }
            set {
                this.typField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:cz-mzcr:ns:dasta:ds4:ds_type")]
    public partial class AnyType {
        
        private System.Xml.XmlElement[] anyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:cz-mzcr:ns:dasta:ds4:ds_dasta")]
    public enum asTypePoradi {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0")]
        Item0,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:cz-mzcr:ns:dasta:ds4:ds_dasta")]
    public enum asTypeTyp {
        
        /// <remarks/>
        D,
        
        /// <remarks/>
        T,
        
        /// <remarks/>
        B,
        
        /// <remarks/>
        F,
        
        /// <remarks/>
        S,
        
        /// <remarks/>
        X,
        
        /// <remarks/>
        M,
        
        /// <remarks/>
        E,
        
        /// <remarks/>
        I,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:cz-mzcr:ns:dasta:ds4:ds_dasta")]
    public enum pdTypeStav {
        
        /// <remarks/>
        A,
        
        /// <remarks/>
        N,
        
        /// <remarks/>
        O,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:cz-mzcr:ns:dasta:ds4:ds_dasta")]
    public partial class osType {
        
        private string obsah2Field;
        
        private osTypeTyp typField;
        
        /// <remarks/>
        public string obsah2 {
            get {
                return this.obsah2Field;
            }
            set {
                this.obsah2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public osTypeTyp typ {
            get {
                return this.typField;
            }
            set {
                this.typField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:cz-mzcr:ns:dasta:ds4:ds_dasta")]
    public enum osTypeTyp {
        
        /// <remarks/>
        C,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:cz-mzcr:ns:dasta:ds4:ds_dasta")]
    public partial class isType {
        
        private asType asField;
        
        private osType[] osField;
        
        private aType aField;
        
        private System.Xml.XmlElement[] anyField;
        
        private AnyType isAnyField;
        
        private string icoField;
        
        private string iczField;
        
        private string icpField;
        
        private string iclField;
        
        private string pczField;
        
        private string oddelField;
        
        private string oavlField;
        
        private sr_typType sr_typField;
        
        private bool sr_typFieldSpecified;
        
        private string sr_poisField;
        
        private string sr_kodField;
        
        private string sr_lekarField;
        
        /// <remarks/>
        public asType @as {
            get {
                return this.asField;
            }
            set {
                this.asField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("os")]
        public osType[] os {
            get {
                return this.osField;
            }
            set {
                this.osField = value;
            }
        }
        
        /// <remarks/>
        public aType a {
            get {
                return this.aField;
            }
            set {
                this.aField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
            }
        }
        
        /// <remarks/>
        public AnyType isAny {
            get {
                return this.isAnyField;
            }
            set {
                this.isAnyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ico {
            get {
                return this.icoField;
            }
            set {
                this.icoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string icz {
            get {
                return this.iczField;
            }
            set {
                this.iczField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string icp {
            get {
                return this.icpField;
            }
            set {
                this.icpField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string icl {
            get {
                return this.iclField;
            }
            set {
                this.iclField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string pcz {
            get {
                return this.pczField;
            }
            set {
                this.pczField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string oddel {
            get {
                return this.oddelField;
            }
            set {
                this.oddelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string oavl {
            get {
                return this.oavlField;
            }
            set {
                this.oavlField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public sr_typType sr_typ {
            get {
                return this.sr_typField;
            }
            set {
                this.sr_typField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool sr_typSpecified {
            get {
                return this.sr_typFieldSpecified;
            }
            set {
                this.sr_typFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string sr_pois {
            get {
                return this.sr_poisField;
            }
            set {
                this.sr_poisField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string sr_kod {
            get {
                return this.sr_kodField;
            }
            set {
                this.sr_kodField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string sr_lekar {
            get {
                return this.sr_lekarField;
            }
            set {
                this.sr_lekarField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:cz-mzcr:ns:dasta:ds4:ds_type")]
    public enum sr_typType {
        
        /// <remarks/>
        L,
        
        /// <remarks/>
        O,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:cz-mzcr:ns:dasta:ds4:ds_type")]
    public partial class garant_datType {
        
        private string id_zpField;
        
        private string id_garantField;
        
        private string odbornostField;
        
        private string id_clkField;
        
        private string role_klicField;
        
        private string role_textField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string id_zp {
            get {
                return this.id_zpField;
            }
            set {
                this.id_zpField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string id_garant {
            get {
                return this.id_garantField;
            }
            set {
                this.id_garantField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string odbornost {
            get {
                return this.odbornostField;
            }
            set {
                this.odbornostField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string id_clk {
            get {
                return this.id_clkField;
            }
            set {
                this.id_clkField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string role_klic {
            get {
                return this.role_klicField;
            }
            set {
                this.role_klicField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string role_text {
            get {
                return this.role_textField;
            }
            set {
                this.role_textField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:cz-mzcr:ns:dasta:ds4:ds_dasta")]
    public partial class pmType {
        
        private asType asField;
        
        private aType aField;
        
        private AnyType pmAnyField;
        
        private string icoField;
        
        private string iczField;
        
        private string icpField;
        
        private string iclField;
        
        private string pczField;
        
        private string oddelField;
        
        private pmTypeSr_typ sr_typField;
        
        private bool sr_typFieldSpecified;
        
        private string sr_poisField;
        
        private string sr_kodField;
        
        private string sr_lekarField;
        
        /// <remarks/>
        public asType @as {
            get {
                return this.asField;
            }
            set {
                this.asField = value;
            }
        }
        
        /// <remarks/>
        public aType a {
            get {
                return this.aField;
            }
            set {
                this.aField = value;
            }
        }
        
        /// <remarks/>
        public AnyType pmAny {
            get {
                return this.pmAnyField;
            }
            set {
                this.pmAnyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ico {
            get {
                return this.icoField;
            }
            set {
                this.icoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string icz {
            get {
                return this.iczField;
            }
            set {
                this.iczField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string icp {
            get {
                return this.icpField;
            }
            set {
                this.icpField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string icl {
            get {
                return this.iclField;
            }
            set {
                this.iclField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string pcz {
            get {
                return this.pczField;
            }
            set {
                this.pczField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string oddel {
            get {
                return this.oddelField;
            }
            set {
                this.oddelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public pmTypeSr_typ sr_typ {
            get {
                return this.sr_typField;
            }
            set {
                this.sr_typField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool sr_typSpecified {
            get {
                return this.sr_typFieldSpecified;
            }
            set {
                this.sr_typFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string sr_pois {
            get {
                return this.sr_poisField;
            }
            set {
                this.sr_poisField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string sr_kod {
            get {
                return this.sr_kodField;
            }
            set {
                this.sr_kodField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string sr_lekar {
            get {
                return this.sr_lekarField;
            }
            set {
                this.sr_lekarField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:cz-mzcr:ns:dasta:ds4:ds_dasta")]
    public enum pmTypeSr_typ {
        
        /// <remarks/>
        L,
        
        /// <remarks/>
        O,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:cz-mzcr:ns:dasta:ds4:ds_dasta")]
    public partial class zdroj_isType {
        
        private AnyType zdrojisAnyField;
        
        private string kod_firmyField;
        
        private string kod_progField;
        
        private string verze_progField;
        
        private string liccis_progField;
        
        /// <remarks/>
        public AnyType zdrojisAny {
            get {
                return this.zdrojisAnyField;
            }
            set {
                this.zdrojisAnyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string kod_firmy {
            get {
                return this.kod_firmyField;
            }
            set {
                this.kod_firmyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string kod_prog {
            get {
                return this.kod_progField;
            }
            set {
                this.kod_progField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string verze_prog {
            get {
                return this.verze_progField;
            }
            set {
                this.verze_progField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string liccis_prog {
            get {
                return this.liccis_progField;
            }
            set {
                this.liccis_progField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:cz-mzcr:ns:dasta:ds4:ds_type")]
    public partial class autorType {
        
        private string id_zpField;
        
        private string id_autorField;
        
        private string odbornostField;
        
        private string id_clkField;
        
        private string role_klicField;
        
        private string role_textField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string id_zp {
            get {
                return this.id_zpField;
            }
            set {
                this.id_zpField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string id_autor {
            get {
                return this.id_autorField;
            }
            set {
                this.id_autorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="NMTOKEN")]
        public string odbornost {
            get {
                return this.odbornostField;
            }
            set {
                this.odbornostField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string id_clk {
            get {
                return this.id_clkField;
            }
            set {
                this.id_clkField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string role_klic {
            get {
                return this.role_klicField;
            }
            set {
                this.role_klicField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string role_text {
            get {
                return this.role_textField;
            }
            set {
                this.role_textField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:cz-mzcr:ns:dasta:ds4:ds_type")]
    public partial class gpsType {
        
        private decimal latField;
        
        private decimal lonField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal lat {
            get {
                return this.latField;
            }
            set {
                this.latField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal lon {
            get {
                return this.lonField;
            }
            set {
                this.lonField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:cz-mzcr:ns:dasta:ds4:ds_dasta")]
    public enum aTypeSr_typ {
        
        /// <remarks/>
        L,
        
        /// <remarks/>
        O,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:cz-mzcr:ns:dasta:ds4:ds_dasta")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="urn:cz-mzcr:ns:dasta:ds4:ds_dasta", IsNullable=false)]
    public partial class dasta {
        
        private zdroj_isType zdroj_isField;
        
        private pmType pmField;
        
        private garant_datType garant_datField;
        
        private object[] itemsField;
        
        private AnyType dastaAnyField;
        
        private string id_souborField;
        
        private string verze_dsField;
        
        private string verze_nclpField;
        
        private dastaBin_priloha bin_prilohaField;
        
        private dastaUR urField;
        
        private string typ_odesmField;
        
        private string ozn_soubField;
        
        private dastaPotvrzeni potvrzeniField;
        
        private bool potvrzeniFieldSpecified;
        
        private System.DateTime dat_vbField;
        
        /// <remarks/>
        public zdroj_isType zdroj_is {
            get {
                return this.zdroj_isField;
            }
            set {
                this.zdroj_isField = value;
            }
        }
        
        /// <remarks/>
        public pmType pm {
            get {
                return this.pmField;
            }
            set {
                this.pmField = value;
            }
        }
        
        /// <remarks/>
        public garant_datType garant_dat {
            get {
                return this.garant_datField;
            }
            set {
                this.garant_datField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("is", typeof(isType))]
        [System.Xml.Serialization.XmlElementAttribute("pd", typeof(pdType))]
        public object[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
        
        /// <remarks/>
        public AnyType dastaAny {
            get {
                return this.dastaAnyField;
            }
            set {
                this.dastaAnyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string id_soubor {
            get {
                return this.id_souborField;
            }
            set {
                this.id_souborField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string verze_ds {
            get {
                return this.verze_dsField;
            }
            set {
                this.verze_dsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string verze_nclp {
            get {
                return this.verze_nclpField;
            }
            set {
                this.verze_nclpField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public dastaBin_priloha bin_priloha {
            get {
                return this.bin_prilohaField;
            }
            set {
                this.bin_prilohaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public dastaUR ur {
            get {
                return this.urField;
            }
            set {
                this.urField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="NMTOKEN")]
        public string typ_odesm {
            get {
                return this.typ_odesmField;
            }
            set {
                this.typ_odesmField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ozn_soub {
            get {
                return this.ozn_soubField;
            }
            set {
                this.ozn_soubField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public dastaPotvrzeni potvrzeni {
            get {
                return this.potvrzeniField;
            }
            set {
                this.potvrzeniField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool potvrzeniSpecified {
            get {
                return this.potvrzeniFieldSpecified;
            }
            set {
                this.potvrzeniFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime dat_vb {
            get {
                return this.dat_vbField;
            }
            set {
                this.dat_vbField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:cz-mzcr:ns:dasta:ds4:ds_dasta")]
    public enum dastaBin_priloha {
        
        /// <remarks/>
        T,
        
        /// <remarks/>
        B,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:cz-mzcr:ns:dasta:ds4:ds_dasta")]
    public enum dastaUR {
        
        /// <remarks/>
        R,
        
        /// <remarks/>
        S,
        
        /// <remarks/>
        U,
        
        /// <remarks/>
        V,
        
        /// <remarks/>
        O,
        
        /// <remarks/>
        B,
        
        /// <remarks/>
        C,
        
        /// <remarks/>
        H,
        
        /// <remarks/>
        T,
        
        /// <remarks/>
        N,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:cz-mzcr:ns:dasta:ds4:ds_dasta")]
    public enum dastaPotvrzeni {
        
        /// <remarks/>
        N,
        
        /// <remarks/>
        P,
    }
}
